### ISSUE TITLE
SUTD Exercise #2 - Flow Cytometry: green navigation buttons are appearing off the screen

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#71] opened 2015-03-09 01:27 UTC
![screen shot 2015-03-08 at 9 26 56 pm](https://cloud.githubusercontent.com/assets/11359229/6548757/e33c3c50-c5d9-11e4-8db8-a1bfbd0efce2.png)

**Comment by pdpinch** [comment] 2015-03-09 13:20
@laleman I think I know where this is, but a URL would be helpful.

**Comment by laleman** [comment] 2015-03-09 15:17
https://scbdev.mit.edu/#view=facs&experiment_id=scb_Experiment_hef9371c8b9d5&assignment_id=sutd_intro_biology_ps2&facs_id=scb_Facs_1cb7ldm24pa3eg

**Comment by ald32** [comment] 2015-03-09 17:46
I see this error on both flow cytometry pages - the sample prep page as well as the run/analyze samples page.

**Comment by laleman** [comment] 2015-03-12 01:22
It is gone from flow cytometry pages, but the same bug is now appearing in microscopy pages for both SUTD exercises (showing examples for SUTD Exercise #1)
- Microscopy set up page (https://scbdev.mit.edu/#view=microscopy&experiment_id=scb_Experiment_2bbedle1nn4bbg&assignment_id=sutd_intro_biology&microscopy_id=scb_Microscopy_1je84ic22i5mf8)
  -Microscopy experiment page (https://scbdev.mit.edu/#view=microscopy&experiment_id=scb_Experiment_2bbedle1nn4bbg&assignment_id=sutd_intro_biology&microscopy_id=scb_Microscopy_1432g2e1gkm9bc)
  ![screen shot 2015-03-11 at 9 18 09 pm](https://cloud.githubusercontent.com/assets/11359229/6610375/b738ba40-c834-11e4-867d-ad6873eb221e.png)
  ![screen shot 2015-03-11 at 9 19 25 pm](https://cloud.githubusercontent.com/assets/11359229/6610379/bcd20ca4-c834-11e4-87ad-013548dc2b36.png)

**Comment by pdpinch** [comment] 2015-03-12 15:34
@laleman we can't reproduce this. Could you try again in an "in cognito" window? If you see it, please paste the URL here.

**Comment by laleman** [comment] 2015-03-12 15:52
Here it is in the incognito window. I put the left and right boundaries to match the left and right boundaries of the graph. The gate drawn in slightly shifted towards the right:

https://scbdev.mit.edu/#view=facs&experiment_id=scb_Experiment_1jh9ge6266j8kq&assignment_id=sutd_intro_biology_ps2&facs_id=scb_Facs_32ddj9jg10bl

**Comment by pdpinch** [comment] 2015-03-12 15:57
Sorry, I'm confused. 

This issue is about the location of the nav buttons. Were you testing the gates? (we are still working on those)

**Comment by laleman** [comment] 2015-03-12 15:58
My bad... yes, wrong thing.. Here you go in an incognito window:

https://scbdev.mit.edu/#view=microscopy&assignment_id=sutd_intro_biology&experiment_id=scb_Experiment_2bbedle1nn4bbg&microscopy_id=scb_Microscopy_1je84ic22i5mf8

**Comment by annagav** [comment] 2015-04-07 17:32
Fixed by #90.

**Closed as completed** 2015-08-06 13:33 UTC
Labels: bug, Medium Priority
